@startwbs
'https://plantuml.com/wbs-diagram

* Транзисторы

 * Биполярные
  * n-p-n
  - p-n-p

 * Полевые
  - С затвором в виде p-n перехода
   * с n-каналом
   - с p-каналом
  * С изолированным затвором
   - Со встроенным каналом
    * с n-каналом
    - с p-каналом
   * С индуцированным каналом
    * с n-каналом
    - с p-каналом

@endwbs