@startmindmap
top to bottom direction
left side
* Теория

** Закон
*** Эксперимент
**** Гипотеза
***** Наблюдение

** Закон
*** Эксперимент
**** Гипотеза
***** Наблюдение

** Закон
*** Эксперимент
**** Гипотеза
***** Наблюдение
@endmindmap

@startuml
top to bottom direction

(Наблюдение А) --> (Гипотеза А)
(Гипотеза А) -down-> (Эксперимент А)
(Эксперимент А) -up-> (Гипотеза А)
(Эксперимент А) --> (Закон А)

(Наблюдение Б) --> (Гипотеза Б)
(Гипотеза Б) -down-> (Эксперимент Б)
(Эксперимент Б) -up-> (Гипотеза Б)
(Эксперимент Б) --> (Закон Б)

(Наблюдение В) --> (Гипотеза В)
(Гипотеза В) -down-> (Эксперимент В)
(Эксперимент В) -up-> (Гипотеза В)
(Эксперимент В) --> (Закон В)

(Закон А) --> (Теория)
(Закон Б) --> (Теория)
(Закон В) --> (Теория)
@enduml
